#!/usr/bin/env bash

message=$(cat << "EOF"
███████╗██╗██████╗ ███████╗████████╗    ███████╗████████╗ ██████╗ ██████╗ 
██╔════╝██║██╔══██╗██╔════╝╚══██╔══╝    ██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗
█████╗  ██║██████╔╝███████╗   ██║       ███████╗   ██║   ██║   ██║██████╔╝
██╔══╝  ██║██╔══██╗╚════██║   ██║       ╚════██║   ██║   ██║   ██║██╔═══╝ 
██║     ██║██║  ██║███████║   ██║       ███████║   ██║   ╚██████╔╝██║     
╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝   ╚═╝       ╚══════╝   ╚═╝    ╚═════╝ ╚═╝     
**************************************************************************************************
"I'll tell you a riddle. You're waiting for a train, a train that will take you far away.
You know where you hope this train will take you, but you don't know for sure."

You found it. Well done. The next dream machine lies just a few addresses higher on your subnet.

Helpful commands: ifconfig, nmap, ssh, man, ping
**************************************************************************************************
EOF
)

cd /home/james
echo "$message" > message
chmod 404 message
echo 'cat message' >> .bashrc

echo "054fdb6a" > flag
chmod 400 flag
chown james:james flag
